// Column shapes that repeat across the schema, defined once.
//
// Not an abstraction layer — each of these returns an ordinary Drizzle column
// builder, and a table that needs something different simply writes it out.
// They exist so that "money" means the same thing in nine places, which is the
// part a reviewer cannot check by eye.

import { char, integer, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * A primary key: a v4 UUID generated by Postgres.
 *
 * **Never a sequential id.** R5 refused one for the order token because a
 * guessable identifier is an enumeration surface, and there is no reason for
 * the rest of the schema to differ. `gen_random_uuid()` is built into Postgres
 * 13+, so this costs no extension.
 */
export const id = () => uuid("id").primaryKey().defaultRandom();

/** When the row was written. Set by the database, never by the app. */
export const createdAt = () =>
	timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

/**
 * When the row last changed.
 *
 * Absent from append-only tables on purpose: an `updated_at` on the event log
 * or on a fit record would imply those rows can be edited, and the whole point
 * of both is that they cannot.
 */
export const updatedAt = () =>
	timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();

/**
 * An amount of money, as a whole number of the currency's smallest unit.
 *
 * **Never floating point** *(R3)*. Money that has been through a float is money
 * that can be out by a franc, and a price he confirmed must be the price the
 * customer is charged. For RWF the minor unit is the franc itself — there are
 * no centimes in circulation.
 *
 * Always paired with a {@link currency} column on the same row, so a figure can
 * never travel without the currency it is counted in.
 *
 * Mirrors `Money` in `src/lib/payments.ts`.
 */
export const money = (name: string) => integer(name);

/**
 * ISO 4217, uppercase. `RWF` is the only value at launch *(R3, R15)*.
 *
 * One of R16's nine reservations: a column that exists and is unused. A second
 * currency changes values in this column and nothing about the model.
 */
export const currency = () => char("currency", { length: 3 }).notNull().default("RWF");

/**
 * A sort position within a parent, set by hand in the dashboard.
 *
 * Plain integer rather than a fractional index: these lists are three to six
 * rows long and he reorders them with arrows, so gap-free renumbering on save
 * is simpler than anything cleverer.
 */
export const position = () => integer("position").notNull().default(0);
