import type { Translation } from "./en";

// The founder has written no Kinyarwanda yet, so every value is null and the
// resolver falls back to English. As he writes, values here replace the
// fallback one key at a time. The keys are required — a new English string
// cannot be forgotten here, only deliberately left null.
//
// **This file being all nulls is what a reservation looks like.** `/rw` is built
// and walkable from day one, `noindex` and unlinked until the flip bar clears:
// shell complete · the four window-display pieces translated · two Kinyarwanda
// readers who are not him. There is no completeness meter, by decision — three
// named things with four pieces behind them are checked by eye *(R9b, R14)*.
//
// Three strings need him rather than us, and are marked below where they sit.
export const rw: Translation = {
	title: null,
	wordmark: null,
	line: null,
	handles: null,

	nav: {
		// Written expecting Kinyarwanda to run about 30% longer than the English.
		collection: null,
		commissions: null,
		making: null,
		story: null,
		label: null,
	},

	footer: {
		wordmark: null,
		collection: null,
		commissions: null,
		making: null,
		story: null,
		contact: null,
		policies: null,
		instagram: null,
		tiktok: null,
		// **His call, item 7b.** Keep the Nguni maxim and name it as Nguni, or
		// carry a Rwandan expression alongside it. No Kinyarwanda proverb has been
		// invented to fill the gap.
		maxim: null,
		maximGloss: null,
		place: null,
		rights: null,
	},

	home: {
		title: null,
		hero: null,
		heroButton: null,
		whoWeAreHeading: null,
		whoWeAre: null,
		collectionKicker: null,
		collectionTheme: null,
		bridge: null,
		windowEmpty: null,
		collectionDoor: null,
		ritualHeading: null,
		ritual: null,
		ritualClose: null,
		ritualDoor: null,
		makingHeading: null,
		makingCondensed: null,
		makingDoor: null,
		closingHeading: null,
		closing: null,
		commissionsDoor: null,
		storyDoor: null,
	},

	collection: {
		title: null,
		heading: null,
		kicker: null,
		bridge: null,
		empty: null,
	},

	piece: {
		// **His call, item 7a.** Does `Ask for this piece` have a Kinyarwanda form,
		// or is it a brand mark that stays English? It is the most important string
		// on the site and only he can judge whether the translation is as good.
		orderButton: null,
		beneathButton: null,
		fit: null,
		kidsRoom: null,
		fitForkHeading: null,
		fitForkMeasurements: null,
		fitForkSize: null,
		storyHeading: null,
		photosHeading: null,
		optionsHeading: null,
		colourway: null,
		cut: null,
		size: null,
		timeframeHeading: null,
		standardTimeframe: null,
		priorityTimeframe: null,
		makingDoor: null,
		commissionsDoor: null,
		back: null,
	},

	commissions: {
		title: null,
		heading: null,
		opening: null,
		whatThisIsHeading: null,
		whatThisIs: null,
		howItGoesHeading: null,
		howItGoes: null,
		moneyHeading: null,
		moneyMoments: null,
		ownership: null,
		costHeading: null,
		cost: null,
		fee: null,
		formHeading: null,
		scene: null,
		scenePrompt: null,
		garment: null,
		garmentUnsure: null,
		name: null,
		contact: null,
		email: null,
		phone: null,
		anythingElse: null,
		channelHeading: null,
		channelNote: null,
		button: null,
		beneathButton: null,
		noImages: null,
		exit: null,
	},

	making: {
		title: null,
		heading: null,
		opening: null,
		steps: null,
		photosHeading: null,
		photos: null,
		timelineHeading: null,
		timeline: null,
		fitHeading: null,
		fit: null,
		tailorHeading: null,
		tailor: null,
		misfitHeading: null,
		misfit: null,
		collectionDoor: null,
		policiesDoor: null,
	},

	story: {
		title: null,
		heading: null,
		philosophyHeading: null,
		philosophy: null,
		brandHeading: null,
		brand: null,
		makerHeading: null,
		maker: null,
		makersEmpty: null,
		abantuHeading: null,
		abantu: null,
		collectionDoor: null,
		commissionsDoor: null,
	},

	contact: {
		title: null,
		heading: null,
		opening: null,
		orderHeading: null,
		order: null,
		orderLink: null,
		orderLost: null,
		commissionHeading: null,
		commission: null,
		elseHeading: null,
		else: null,
		name: null,
		reply: null,
		message: null,
		button: null,
		whatsappHeading: null,
		whatsapp: null,
	},

	policies: {
		title: null,
		heading: null,
		opening: null,
		fitHeading: null,
		fit: null,
		alterationHeading: null,
		alteration: null,
		deliveryHeading: null,
		delivery: null,
		makingHeading: null,
		making: null,
		handsHeading: null,
		hands: null,
		detailsHeading: null,
		details: null,
		stoppingHeading: null,
		stopping: null,
		commissionHeading: null,
		commission: null,
		commissionMoneyHeading: null,
		commissionMoney: null,
	},
};
